version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-converter-web
    ports:
      - "3030:3030"
    restart: unless-stopped
    volumes:
      - converted_files:/app/converted_files
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  converted_files:
    driver: local